import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/app/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row">
          <div className="min-h-screen w-[300px] bg-gray-500">
            <Nav/>
          </div>
          <div className="w-full min-h-screen flex justify-center">
           {children}
          </div>
        </div>
        </body>
    </html>
  );
}
